name: Build Windows MSVC (Kodi Leia)

on:
  workflow_dispatch:

env:
  ADDON_ID: inputstream.adaptive_yt

jobs:
  build-windows:
    name: Windows MSVC Build
    runs-on: windows-latest

    steps:
      - name: Checkout Kodi repo (Leia)
        uses: actions/checkout@v4
        with:
          repository: xbmc/xbmc
          ref: Leia
          path: xbmc

      - name: Checkout addon repo
        uses: actions/checkout@v4
        with:
          path: addon/${{ env.ADDON_ID }}

      #- name: Create build directory
      #  run: mkdir build -Force

      #- name: Restore Kodi Depends Cache
      #  uses: actions/cache@v4
      #  with:
      #    path: |
      #      build/build
      #      build/${{ env.ADDON_ID }}-prefix
      #    key: ${{ env.ADDON_ID }}-deps-${{ hashFiles('addon/**') }}

      #- name: Debug workspace tree
      #  run: |
      #    Write-Host "Workspace:"
      #    Get-ChildItem ${{ github.workspace }} -Depth 3

      - name: Create addon definition file for custom addon ID
        run: |
          $addonDefDir = "${{ github.workspace }}\xbmc\cmake\addons\addons"
          New-Item -ItemType Directory -Path $addonDefDir -Force | Out-Null
          $filePath = Join-Path $addonDefDir "${{ env.ADDON_ID }}.txt"
          Set-Content -Path $filePath -Value "inputstream.adaptive_yt https://github.com/doko-desuka/inputstream.adaptive_yt/ Leia"
          Write-Host "Created addon definition file: $filePath"

      - name: Configure CMake
        run: |
          mkdir build_zips
          mkdir build
          cd build
          cmake `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DENABLE_ADDONS=OFF `
            -DBUILD_BUNDLED_ADDONS=OFF `
            -DADDONS_TO_BUILD="${{ env.ADDON_ID }}" `
            -DADDON_SRC_PREFIX="${{ github.workspace }}/addon" `
            -DPACKAGE_ZIP=1 `
            -DPACKAGE_DIR="${{ github.workspace }}/build_zips"
            "${{ github.workspace }}/xbmc/cmake/addons"

      - name: Build Addon
        run: |
          cd build
          cmake --build . --config Release -- /m

      - name: Debug workspace tree
        run: |
          Write-Host "Workspace:"
          Get-ChildItem ${{ github.workspace }} -Depth 3
      
      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ADDON_ID }}_windows_msvc
          path: xbmc/cmake/addons/output/addons/${{ env.ADDON_ID }}/*.zip
